import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Grid from '@mui/material/Grid';
import { Button, Typography } from '@mui/material';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Course Selling App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Grid container style={{padding: "5vw"}}>
              <Grid item xs={12} md={6} lg={6}>
                  <div style={{marginTop: 100}}>
                      <Typography variant={"h2"}>
                          Coursera Admin
                      </Typography>
                      <Typography variant={"h5"}>
                          A place to learn, earn and grow
                      </Typography>
                      {/*!userLoading && !userEmail && <div style={{display: "flex", marginTop: 20}}>
                          <div style={{marginRight: 10}}>
                              <Button
                                  size={"large"}
                                  variant={"contained"}
                                  onClick={() => {
                                      navigate("/signup")
                                  }}
                              >Signup</Button>
                          </div>
                          <div>
                              <Button
                                  size={"large"}
                                  variant={"contained"}
                                  onClick={() => {
                                      navigate("/signin")
                                  }}
                              >Signin</Button>
                          </div>
                      </div>*/}
                  </div>
                  <div>
                  </div>
              </Grid>
              <Grid item xs={12} md={6} lg={6}  style={{marginTop: 20}}>
                  <img src={"/class.jpeg"} width={"100%"} />
              </Grid>
          </Grid>
        </div>
      </main>
    </>
  )
}
